int _putchar(char name);
int print_alphabet(void);
int print_alphabet_x10(void);
int _islower(int character);
int _isalpha(int character);
int print_sign(num);
int _abs(num);
int print_last_digit(int num);
int jack_bauer(void);
int times_table(void);
int add(num_one, num_two);
int print_to_98(num);
int print_times_table(num);
